replicaCount: 2
image:
  repository: 787107040006.dkr.ecr.eu-north-1.amazonaws.com/bewerbungmanager-api
  tag: "3b43702a2800963830327eff667dedfd6e9e8e27"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
containerPort: 3000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 20
ingress:
  enabled: true
  className: alb
  host: api.example.com
