replicaCount: 2
image:
  repository: 787107040006.dkr.ecr.eu-north-1.amazonaws.com/bewerbungmanager-api
  tag: "f58f779d82508081eb59861d1727b1fdf5121360"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
containerPort: 3000
env:
  GOOGLE_CLIENT_ID: "381652459210-fm86v7drqcfqcpl9vpcdtbar305517l1.apps.googleusercontent.com"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 20
ingress:
  enabled: true
  className: alb
  host: api.example.com
