FROM node:22-alpine

WORKDIR /app

# Benötigt für argon2 (node-gyp)
RUN apk add --no-cache python3 make g++

COPY package*.json ./

RUN npm ci

COPY prisma ./prisma

RUN npx prisma generate

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]